# This is a basic workflow to help you get started with Actions

name: CI
run-name: Running CI jobs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ "master", "release/**" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Node Env
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Yarn
        run: npm i -g yarn

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: '**/*.{test,spec}.{js,jsx,ts,tsx}'

      - name: Prepare coverage include paths
        id: prepare-coverage
        run: |
          changed_files="${{ steps.changed-files.outputs.all_changed_files }}"
          coverage_include=$(echo "$changed_files" | sed 's|[^ ]*|--coverage.include=&|g')
          echo "COVERAGE_INCLUDE=$coverage_include" >> $GITHUB_ENV

      - name: Install dependencies
        run: yarn
      
      - name: Build
        run: yarn build

      - name: Run tests
        run: 'yarn test --run --coverage.enabled --coverage.all=false $COVERAGE_INCLUDE'

      - name: Report coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
