# This is a basic workflow to help you get started with Actions

name: CI
run-name: Running CI jobs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master", "release/**" ]
  pull_request:
    branches: [ "master", "release/**" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Node Env
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Yarn
        run: npm i -g yarn

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn

      - name: Build and run tests
        run: |
          yarn build
          yarn test:coverage

      - name: Report coverage
        if: always()
        uses: actions/vitest-coverage-report-action@v2
